### ISSUE TITLE
Reader View

### ISSUE THREAD

**Issue by pablo03v** [msasikanth/twine#107]
**Is your feature request related to a problem? Please describe.**
Instead of opening the website I'd love to view the articles directly inside the app alternatively

**Describe the solution you'd like**
A new view would open (preferably not a Bottom sheet as there's already one) with the date, title, image, body, author and so on

**Additional context**
Not necessary imho

**Comment by msasikanth** [comment]
Not all sources provide enough content to generate a good reader view. They often just end up with read more button. That's why decided to open web page instead.

**Comment by pablo03v** [comment]
Mmm 🤔, what about an in-app browser then? My problem is that I use LinkSheet which pops up for every link. With the Reader app tho I open many many links which makes it annoying. 

Additionally if I were able to, would I be allowed to create a fork and add a reader view? I think it's very necessary for an rss READER after all ;)

**Comment by pablo03v** [comment]
Plus "Read you" fixes your issue with the content being incomplete by parsing the linked website.

**Comment by msasikanth** [comment]
You can set the app to open links in-app in the settings.

**Comment by pablo03v** [comment]
I just can't find the settings xD. I do enjoy the apps design a lot!

**Comment by msasikanth** [comment]
Twine finally support showing content in a reader view

![422046044_293110617078023_3230646806147610496_n](https://github.com/msasikanth/twine/assets/6140516/4b96757e-9ecd-411b-90f7-51022a977b02)
