### ISSUE TITLE
Incorrect timestamps for the posts

### ISSUE THREAD

**Issue by pablo03v** [msasikanth/twine#108]
**Describe the bug**
Instead of showing the actual release date of rss items it says '0 minutes ago'.

**To Reproduce**
1. Add haveibeenpawned rss
2. See same result

**Screenshots**
![9c75e1a4-4c7e-4880-8594-d5904282e115](https://github.com/msasikanth/twine/assets/93644977/46b26269-d44f-437d-ae87-0b487233bbbb)

**Device Information**
 - Device: Pixel 4a (5g)
 - OS: 13 (latest)
 - App Version: 1.2.0 (fdroid)

**Stacktrace**
Not present in my present lol

**Comment by msasikanth** [comment]
Not an issue in latest version of the app from Play Store. Closing the issue.

**Comment by pablo03v** [comment]
great! sorry I opened this then ;)

**Comment by RWCoding58** [comment]
Experiencing the same bug with some other rss feeds, namely Github atom feeds (commits and releases, for example https://github.com/msasikanth/twine/releases.atom) and some foreign online news website called mothership.sg (the feed url being https://mothership.sg/feed/). It pretty much refetches the same post everytime a refresh occurs, changing the post timestamp to when it was refreshed

**Comment by msasikanth** [comment]
> Experiencing the same bug with some other rss feeds, namely Github atom feeds (commits and releases, for example https://github.com/msasikanth/twine/releases.atom) and some foreign online news website called mothership.sg (the feed url being https://mothership.sg/feed/). It pretty much refetches the same post everytime a refresh occurs, changing the post timestamp to when it was refreshed

Ah, both of these links use date formats that are not commonly used by other feeds. Will look into it.

**Comment by RWCoding58** [comment]
> Experiencing the same bug with some other rss feeds, namely Github atom feeds (commits and releases, for example https://github.com/msasikanth/twine/releases.atom) and some foreign online news website called mothership.sg (the feed url being https://mothership.sg/feed/). It pretty much refetches the same post everytime a refresh occurs, changing the post timestamp to when it was refreshed

The latest release (1.29.0) seems to have fixed the GitHub feeds, but the Mothership one still has the same bug.

**Comment by msasikanth** [comment]
> > Experiencing the same bug with some other rss feeds, namely Github atom feeds (commits and releases, for example https://github.com/msasikanth/twine/releases.atom) and some foreign online news website called mothership.sg (the feed url being https://mothership.sg/feed/). It pretty much refetches the same post everytime a refresh occurs, changing the post timestamp to when it was refreshed
> 
> The latest release (1.29.0) seems to have fixed the GitHub feeds, but the Mothership one still has the same bug.

Oh, thanks. Looks like I missed that format. Added it, will be available in next release.
