### ISSUE TITLE
Mastodon user feeds are incorrectly displayed

### ISSUE THREAD

**Issue by msfjarvis** [msasikanth/twine#114]
**Describe the bug**
Mastodon creates auto-generated RSS feeds for users. These only have descriptions containing the post contents and no titles which results in an empty list of items being displayed.

**To Reproduce**
1. Add this feed URL: https://mastodon.social/@hackbod.rss
2. Observe all items have empty titles

**Comment by msasikanth** [comment]
eb265663d14bb0ae21dba71425e881e8af567e5d fixes this issue

**Comment by msasikanth** [comment]
We use the description as a title in case a title is not present. If both of them are not present, we just skip that post.
