### ISSUE TITLE
Articles don’t open on iOS

### ISSUE THREAD

**Issue by SebastianAigner** [msasikanth/twine#129]
https://github.com/msasikanth/twine/assets/2178959/5b1263d8-f60c-4f09-9471-843b20ea6e4d

**Comment by msasikanth** [comment]
~~Can you share a link to this feed, please?~~

**Comment by msasikanth** [comment]
Weird, I have found the blog and added it. But it's opening it fine for me. For debugging purposes, by any chance you don't have Safari on your device? or what's your default browser?

If you can provide me the OS details as well that would be extremely helpful @SebastianAigner 🙏🏾

https://github.com/msasikanth/twine/assets/6140516/a1dbc5a5-30d2-4939-aa9e-8ed40b5c40d3

**Comment by SebastianAigner** [comment]
iOS 17.1, I have Safari installed. Seems to only be the case if the blog in question is the *only* feed added. When other feeds are added, it works mysteriously.

**Comment by msasikanth** [comment]
Oh, that's an interesting bug. Let me look into it further 👀
