### ISSUE TITLE
Overscroll looks a bit odd on iOS

### ISSUE THREAD

**Issue by SebastianAigner** [msasikanth/twine#130]
Rather minor glitch, but figured I'd still point it out since I just ran into it :) 

https://github.com/msasikanth/twine/assets/2178959/ddda321c-f5ee-46e5-845b-e42b8549989a

**Comment by msasikanth** [comment]
Oh, it's a known thing. The blur is shown below over scroll for some reason, I never really got around to looking into it. But it's in my backlog 👍🏾
