### ISSUE TITLE
Keyboard done action not working on iOS when adding feed

### ISSUE THREAD

**Issue by acousticksan** [msasikanth/twine#14]
**ios version:** 16.4.1
**device model:** iPhone Xr

ImeAction.Done don't work. It add new line at TextField

[Issue at Compose Rep](https://github.com/JetBrains/compose-multiplatform/issues/2794 )

**Comment by msasikanth** [comment]
Thanks for creating the issue, I am aware of the issue and trying to figure out a solution I can take in the meantime (probably updating the UI to have a "add" button)
