### ISSUE TITLE
Cannot add RSS v1.0 feed

### ISSUE THREAD

**Issue by akinsho** [msasikanth/twine#183]
**Description**
Hi,

Thanks for your work on this project, it's been a really pleasant experience using this app.
On to the issue, I just tried to add the following RSS feed (http://ln.hixie.ch/rss/html) via the app and it errors that the feed is not a valid RSS feed. I had a look for similar issues and found that you use a validator to check what should be supported, but according to this validator this feed is ok.

https://validator.w3.org/feed/check.cgi?url=https://ln.hixie.ch/rss/html 

**To Reproduce**
1. Open bottom sheet and hit the "add feed" button in Twine
2. Add the link `http://ln.hixie.ch/rss/html`

**Screenshots**
![Screenshot_20231205-172911](https://github.com/msasikanth/twine/assets/22454918/1c90a5b4-62cd-4750-8573-39ffc41c464c)

**Device Information**
 - Device: Pixel 8 Pro
 - OS: Android 14
 - App Version: 1.28.1

**Stacktrace**
If present, add stacktrace to help debug the issue faster.

**Comment by msasikanth** [comment]
Thanks for raising the issue. It looks like the feed you provided is a RSS v1.0 feed, I mainly tested and added support for RSS v2.0 and Atom feeds. Let me look into it.

**Comment by creepy-pasta101** [comment]
Well I have the same problem as well...
`https://connect.biorxiv.org/biorxiv_xml.php?subject=all`

I don't have much experience with multiplatform, but since you are using direct parsing instead of serialization(AFAIK) I guess you need to tweak the parser as well (To accept RSS 1.0 format)??

**Comment by msasikanth** [comment]
> Well I have the same problem as well...
> 
> `https://connect.biorxiv.org/biorxiv_xml.php?subject=all`
> 
> 
> 
> I don't have much experience with multiplatform, but since you are using direct parsing instead of serialization(AFAIK) I guess you need to tweak the parser as well (To accept RSS 1.0 format)??

Yes, I am making changes to resolve this issue. Will finish it at some point. Right now my immediate focus is on other aspects of the app. Like folders and improved adding feed experience.

**Comment by yolobnb** [comment]
@msasikanth isn't it time to take a look into this issue? There have been a lot of visual changes within the app until now. As an RSS reader, shouldn't the functionality of adding RSS feeds be a primary goal and concern? I am surprised that there have been no updates on this one.

I deeply appreciate your time and effort in the development and maintenance of the application. I have been thoroughly enjoying the experience as were some of my friends, a lot of my colleagues, and people at work when I initially recommended this. A lot of them ditched this, however, for other readers just due to this issue. Hoping to see an update on this one.

**Comment by msasikanth** [comment]
> @msasikanth isn't it time to take a look into this issue? There have been a lot of visual changes within the app until now. As an RSS reader, shouldn't the functionality of adding RSS feeds be a primary goal and concern? I am surprised that there have been no updates on this one.
> 
> I deeply appreciate your time and effort in the development and maintenance of the application. I have been thoroughly enjoying the experience as were some of my friends, a lot of my colleagues, and people at work when I initially recommended this. A lot of them ditched this, however, for other readers just due to this issue. Hoping to see an update on this one.

It's an open-source project, you are free to contribute if it's really important for you. As I mentioned in my previous comment, I have a handful of priorities I want to get done first. 

Compared to something like groups/folders or improving performance and memory efficiency. This is low on my list, based on the number of people who requested it. Don't get me wrong, I will eventually get to this and JSON feed, but it will be when I have finished my other tasks and I have time from my work. It's not my full time job.

**Comment by Drsheppard01** [comment]
I'm not sure, but I think this library can help you https://github.com/muhrifqii/ParseRSS
