### ISSUE TITLE
Articles from an RSS feed are continuously reported as being 0 mins old

### ISSUE THREAD

**Issue by akinsho** [msasikanth/twine#186]
**Describe the bug**
Following the latest release of v1.29.0 (115) I find that with the (welcome) addition of a read status one of my feeds i.e. [Google AI blog](https://blog.research.google/) ([RSS](https://feeds.feedburner.com/blogspot/gJZg)) always reports the time for all articles as 0 mins since posted. This does increase over time for however long I leave it but once I refresh the feed it resets to 0.

**To Reproduce**
1. Add RSS feed for google AI blog (linked in the issue)
2. Add it Twine
3. All articles will be shown as 0 mins since posted
4. Wait a few mins then refresh, they are reset again

**Screenshots**
![Screenshot_20231212-103450](https://github.com/msasikanth/twine/assets/22454918/b8c48fe0-7c6b-4acd-b9e8-c35b0e86198d)

**Device Information**
 - Device: Pixel 8 pro
 - OS: Android 14
 - App Version 1.29.0

**Comment by msasikanth** [comment]
Thanks for reporting @akinsho , can you also link me to some of the other feeds that might potential be showing similar date issue?

**Comment by msasikanth** [comment]
If this is the only one, I have resolved it and should be available in next update and I can close this issue.

**Comment by akinsho** [comment]
@msasikanth that's the only one I've noticed actually. I didn't want to assume whether or not it's general but can't see any other issues 👍🏾

EDIT: Thanks for the quick fix
