### ISSUE TITLE
App keep closing itself

### ISSUE THREAD

**Issue by haildriver** [msasikanth/twine#219]
**Describe the bug**
App closes itslef when you mark all read and click next feed sub.

**To Reproduce**
1. Open all feed drawer.
2. Mark one feed as all read
3. Click on the feed below that
4. App closes itself

**Device Information**
 - Device: [MIUI GLOBAL 12.0.19]
 - OS: [Android 10]
 - App Version [1.30.1]

**Comment by msasikanth** [comment]
Hi, thanks for reporting. Can you also post the links to the feeds that are causing this issue?

**Comment by msasikanth** [comment]
Closing because of no updates. I will continue to monitor this on Sentry and resolve crashes as they occur.
