### ISSUE TITLE
Support feed folders

### ISSUE THREAD

**Issue by ghobs91** [msasikanth/twine#234]
For those who have organized their feeds into folders by topic, the OPML file also has that information. It would be super handy to have Twine organize our feeds into those folders when we import!

**Comment by AraAraOwO** [comment]
Bump 
I am nit much good at app development and never learnt kotlin so I can’t try to contribute as of now. Sorry for that

**Comment by msasikanth** [comment]
Twine now has support for feed groups, it should be available in the next release

**Comment by ghobs91** [comment]
> Twine now has support for feed groups, it should be available in the next release

Awesome work! Thanks so much
