### ISSUE TITLE
iOS version twine keep crash after update to 1.32.0(152)

### ISSUE THREAD

**Issue by Popeye-sz** [msasikanth/twine#237]
**Describe the bug**
iOS version twine keep crash after updated to 1.32.0(152) version

**To Reproduce**
1. Open twine
2. scroll tableview or do nothing
3. App will crash or abort 

**Screenshots**
https://github.com/msasikanth/twine/assets/104444708/6f4c9fff-69d7-4d31-ac6e-5cd13c4cd5d7

**Device Information**
 - Device: iPhone 11
 - OS: iOS 16.7
 - App Version 1.32.0(152)

**Stacktrace**
- null

**Comment by msasikanth** [comment]
Got it, jut to confirm the app is crashing even after uninstalling and reinstalling it? I am just trying to narrow down whether a particular feed is causing it.

**Comment by msasikanth** [comment]
Closing because of no updates. I will continue to monitor this on Sentry and resolve crashes as they occur.
