### ISSUE TITLE
Support marking article as read

### ISSUE THREAD

**Issue by NathanealV** [msasikanth/twine#256]
Sometimes, RSS feeds have articles which I don't necessarily want to read but clutter up the feed, and marking all posts as read would not be ideal. It would be really helpful to add this feature (whether through a left/right swipe gesture and/or a button where the bookmark and share buttons are) to help organise my feed!

**Comment by msasikanth** [comment]
Currently you can mark all posts as read from the feed menu in the bottom sheet. I will look into providing it per post in future.
