### ISSUE TITLE
Twine Crash when fetching website content

### ISSUE THREAD

**Issue by PitiBouchon** [msasikanth/twine#280]
**Describe the bug**
Twine crash when fetching website content

**To Reproduce**
The rss link used is : https://cglab.ca/~abeinges/blah/rss.xml

1. Click on a post
2. Click on the button to fetch the post content from the website

**Comment by FreedomChuks** [comment]
this is happening because website content is using an unsecured Protocol HTTP

**Comment by msasikanth** [comment]
You can keep this open, I am working in addressing the crash itself.

**Comment by PitiBouchon** [comment]
Ah yes my bad, I thought it was already fixed for the next release
