### ISSUE TITLE
Can't Add RSS feed

### ISSUE THREAD

**Issue by haildriver** [msasikanth/twine#283]
**Describe the bug**
I get "input = 1" error when I add mitter rss

**To Reproduce**
1. Go to Twine
2. Click on 'Add feed'
3. Add 'https://nitter.adminforge.de/depthsofwiki/rss'

**Device Information**
 - Device: [Poco C3]
 - OS: [e.g. Android 11]
 - App Version [e.g. 1.33.0]

**Comment by FreedomChuks** [comment]
this issue similar with https://github.com/msasikanth/twine/issues/280
https://nitter.adminforge.de/depthsofwiki/rss redirect to HTTP which is an unsecured Protocol

**Comment by msasikanth** [comment]
> this issue similar with #280 https://nitter.adminforge.de/depthsofwiki/rss redirect to HTTP which is an unsecured Protocol

Hey. It's a different issue. The link is properly using `https` protocol. The issue seems related to content charset decoding after fetching the feed. I am looking into this issue.
