### ISSUE TITLE
Old Articles Surface above recent articles 

### ISSUE THREAD

**Issue by haildriver** [msasikanth/twine#284]
**Describe the bug**
Despite Sorting by recent or deleting articles older than a week, older articles from certain websites stays on top 

**To Reproduce**
1. Go to 'Add feed'
2. Paste  'https://asteriskmag.com/feed'
3. See error

**Device Information**
 - Device: [Poco C3]
 - OS: [e.g. Android 11]
 - App Version [e.g. 1.33.0]

**Comment by msasikanth** [comment]
Certain sources keep sending the same articles every time app refreshes to fetch data. So, a new instance the same article is created in db and end up showing in list again. Unfortunately there is nothing I can do about it. 

I can keep track of deleted articles links and keep checking with them, but that seems excessive and wasteful of resources of devices.
