### ISSUE TITLE
Add support for changing app language

### ISSUE THREAD

**Issue by cfoellmann** [msasikanth/twine#290]
Have you thought about providing translation support?

I am looking for an rss app for our staff and would be happy to provide German and maybe polish translations

**Comment by msasikanth** [comment]
Yes! Thank you. Right now you can find the English version of the strings [here](https://github.com/msasikanth/twine/blob/main/resources/strings/src/commonMain/kotlin/dev/sasikanth/rss/reader/resources/strings/EnTwineStrings.kt). What I would recommend doing is, creating a Google Sheet with key and translated string for the language. I can then create the Kotlin class.

Or if you are comfortable with forking and cloning the project, and creating new Kotlin classes, that would be great as well. Here is the process.

1. Edit the `Locales` object in `TwineStrings.kt` to add a new locale ISO tag. In your case `de` for Germany and `pl` for Polish.

```kt
object Locales {
  const val EN = "en"
  const val DE = "de"
  // more locales
}
```

2. Then create a new file under the same package as `EnTwineStrings`, you just have to attach the ISO prefix to the `TwineStrings` name. So, we will have `DeTwineStrings`.

3. In that file create a new variable called `DeTwineStrings` and initialise the `TwineStrings` data class to add your translations.

```kt
@LyricistStrings(languageTag = Locales.DE, default = false)
val DeTwineStrings = TwineStrings(
  // translations
)
```

4. Run `./gradlew spotlessApply` task before raising a PR to make sure code style checks pass.

If this process is a lot, feel free to fallback to just providing me with the Google Sheet, and I can make these changes.

**Comment by cfoellmann** [comment]
Thanks for the fast reply.
I am on vacation soon but will look into it when I get back

**Comment by FreedomChuks** [comment]
I was able to raise a PR for addition of a german translation

**Comment by FreedomChuks** [comment]
I would add support for other languages at the weekend
