### ISSUE TITLE
Importing opml option not working 

### ISSUE THREAD

**Issue by Vamsi-2001** [msasikanth/twine#308]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Device Information**
 - Device: [e.g. Pixel 7]
 - OS: [e.g. Android 13]
 - App Version [e.g. 1.0.0]

**Stacktrace**
If present, add stacktrace to help debug the issue faster.

**Comment by msasikanth** [comment]
Hi, can you share the OPML you tried? That would help with reproducing the issue

**Comment by msasikanth** [comment]
@Vamsi-2001 can you provide the OPML file you tried, so that I can experiment with it and try to reproduce the issue?

**Comment by Vamsi-2001** [comment]
> @Vamsi-2001 can you provide the OPML file you tried, so that I can experiment with it and try to reproduce the issue? 

Yeah sure @msasikanth 
[Link](https://sidebar.io/webring/opml)
