### ISSUE TITLE
App crashes when swiping up (Android 12)

### ISSUE THREAD

**Issue by KiraiEEE** [msasikanth/twine#31]
Upon launching the app for the first time after downloading it from the Play Store, I encountered a crash when swiping up on my Redmi Note 9S Global device running Android 12 (MIUI 14). 

(After swiping up, the app crashes and closes abruptly)

- Device: Redmi Note 9S Global
- Android Version: Android 12
- MIUI Version: MIUI 14

I have not encountered any similar issues with other apps made with Compose.

**Comment by KiraiEEE** [comment]
Haha, I just uninstalled and reinstalled the app from the Play Store to screen record the issue, and magically, it works perfectly fine. The crash is nowhere to be found! XD (Looks like the app is afraid of socials)

**Comment by msasikanth** [comment]
Hi, there was in fact an issue with older version of the app on certain devices. That is resolved in the newer version.
