### ISSUE TITLE
App closes randomly

### ISSUE THREAD

**Issue by ghost** [msasikanth/twine#320]
**Describe the bug**
When I try to use the App it opens, loads my Feeds and then shuts down. This happens every time when I try to use it. 

**To Reproduce**
1. Open the App
2. It will close itself after nearly 3 seconds

**Screenshots**
-

**Device Information**
 - Device: iPhone 15 Pro
 - OS: iOS 17.3.1
 - App Version: 1.36.0

**Stacktrace**
-

**Comment by FreedomChuks** [comment]
can you post the link to the feeds you try to load?

**Comment by msasikanth** [comment]
Thanks for reporting the issue. I noticed a weird crash report that matches the summary you provided and with your device specs.

I am already looking into the issue 👍🏾

**Comment by msasikanth** [comment]
I have pushed an update to handle this issue better, should be available hopefully in the next few hours 🤞🏾

**Comment by ghost** [comment]
I did the update and it seems to work fine. Thanks for the quick help!
