### ISSUE TITLE
Random Crash 

### ISSUE THREAD

**Issue by lhenriquezc** [msasikanth/twine#327]
Crashing on Pixel

Keep crashing randomly on certain feed but more often on Android police an XDA developers feed s, I'm using Pixel Pro on latest Android 14 beta

**Device Information**
 Pixel 8 Pro
 App version 1.37.0 (244)
Build number AP21.240119.009

**Comment by msasikanth** [comment]
Thanks for raising the issue. Just to confirm the crash is happening in the list as you are loading items from those sources or it's crashing when you click on it and trying to load reader view?

**Comment by lhenriquezc** [comment]
it's crashing when i click on it and trying to load reader view

**Comment by lhenriquezc** [comment]
> Thanks for raising the issue. Just to confirm the crash is happening in the list as you are loading items from those sources or it's crashing when you click on it and trying to load reader view?

 it's crashing when you click on it and trying to load reader view

**Comment by msasikanth** [comment]
Issue will be resolved in the next update.
