### ISSUE TITLE
Add support for card view

### ISSUE THREAD

**Issue by alagman** [msasikanth/twine#341]
Please add option for card view similar with Feeder app.

![Screenshot_20240227_225147_Feeder](https://github.com/msasikanth/twine/assets/39099813/a906deda-06cd-4dcf-9b54-5dc59f8c1e83)

![Screenshot_20240227_224917_Feeder](https://github.com/msasikanth/twine/assets/39099813/6d49901d-3b72-4ded-8151-db477a68e18d)

**Comment by msasikanth** [comment]
Not planned
