### ISSUE TITLE
"Fetch Full Articles by Default" option

### ISSUE THREAD

**Issue by theabhishekbhujang** [msasikanth/twine#354]
Introduce an option in settings labeled 'Fetch Full Articles by Default'. This functionality would automatically retrieve complete articles from websites/feeds, removing the need for users to constantly click a button.

**Comment by msasikanth** [comment]
It's already present in the feed info sheet for configuring per feed. Some sources are not well configured to always fetch source articles. That's why it available as per feed configuration.

**Comment by theabhishekbhujang** [comment]
Agreed. But having an option to do it by default automatically reduces some clicks and also it can be turned off if not required from the settings.

**Comment by msasikanth** [comment]
Hmm, fair enough. At this point, it's not planned. But I might pick this up in future once I finished the other planned work.

**Comment by theabhishekbhujang** [comment]
Sure. Thank you!
