### ISSUE TITLE
Add folders + article size option

### ISSUE THREAD

**Issue by JayBFC** [msasikanth/twine#358]
Allowing users to create folders would make for a much more organised experience. You could add feeds that you've manually added into a folder, such as Sport, Tech etc. You can then switch between different topics easily.

Also, being able to change the size of articles in the main feed list would allow users to have an easier time scrolling through posts. Some people prefer a large section of the screen per post with a large image preview, some people would prefer a condensed list of all the articles with no pictures at all etc.

**Comment by msasikanth** [comment]
duplicate https://github.com/msasikanth/twine/issues/234
