### ISSUE TITLE
[Feature] AI summarisation 

### ISSUE THREAD

**Issue by srt54558** [msasikanth/twine#363]
**Is your feature request related to a problem? Please describe.**
Yes a bit... Some articles are very long but mainly try to keep the user at the page. It's just repeating or explaining something too long. 

**Describe the solution you'd like**
AI powered summarization (maybe even On-device using gamma?) with one click. Like the experimental version for Google Chrome, where you get 3 main points of a page. I don't know how hard this is to implement, and I wouldn't be upset if it isn't possible, but this would make this RSS reader to the NEXT level!

**Additional context**
![Screenshot_20240305-224737.png](https://github.com/msasikanth/twine/assets/90862487/5ff35081-db60-4bf2-83e2-d3789343058b)

**Comment by msasikanth** [comment]
I am not interested in doing this. Since I don't own the data from the websites, I am uncomfortable providing the AI summarization of 3rd party publications that might not be willing to send that data to any AI training models.
