### ISSUE TITLE
Adding RSS feed fails

### ISSUE THREAD

**Issue by yolobnb** [msasikanth/twine#373]
**Describe the bug**
None of the RSS links from the following website works in Twine:

https://corporate.dw.com/en/rss/s-31500

This popular website works fine with other RSS readers (I cross-checked to make sure it wasn't a general issue). 

**To Reproduce**
1. Go to Twine
2. Click on 'Add feed'
3. Paste any of the RSS links in the field.

**Screenshots**
![image](https://github.com/msasikanth/twine/assets/98680372/7b7c8958-3db3-4c32-b4c3-850bd94ba7c2)

**Device Information**
 - OS: Android 14
 - App Version: 1.38.0

**Comment by msasikanth** [comment]
Please use ATOM feed links, the RSS feed links in the given link are RSS v1.0 which are not supported yet.

#183
