### ISSUE TITLE
Offer to subscribe to post comment feeds? 

### ISSUE THREAD

**Issue by josb** [msasikanth/twine#376]
I am honestly not sure if this is even feasible, but I thought I'd ask.

I subscribe to https://www.nakedcapitalism.com/feed
As a result, Twine shows posts like
https://www.nakedcapitalism.com/2024/03/links-3-9-2024.html which it allows me to read.

That post also has its own comment feed, a link to which appears right before the comments start:
https://www.nakedcapitalism.com/2024/03/links-3-9-2024.html/feed

Is it possible for Twine to offer to subscribe to that comment feed at the bottom when it shows the post?

**Comment by msasikanth** [comment]
No, we show a comments icon when there are comments in the actual feed. In order to subscribe to a comments feed, you would have to add that feed link.

**Comment by josb** [comment]
I figured as much.

Thank you for the quick response, @msasikanth! 🙏
