### ISSUE TITLE
F-Droid Release

### ISSUE THREAD

**Issue by jcperil** [msasikanth/twine#38]
**Is your feature request related to a problem? Please describe.**
Can you add Reader to F-Droid?

**Describe the solution you'd like**
[This is the inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/) that must be met to be able to submit. More info about submitting can be [found here](https://f-droid.org/en/contribute/).

[Here is the issue tracker](https://gitlab.com/fdroid/rfp/-/issues) to request your package to be available on F-Droid. After submitting, they can assist on what is needed to be done (if anything) to get it on F-Droid.

**Comment by VipinVIP** [comment]
Maybe add a github release too. Currently as an android 11 user , i cant install the app from playstore ( maybe they didn't update ? ) and building the app from source need so much downloading of dependencies.

**Comment by msasikanth** [comment]
> Maybe add a github release too. Currently as an android 11 user , i cant install the app from playstore ( maybe they didn't update ? ) and building the app from source need so much downloading of dependencies. 

App supports Android 8 and above now. You should be able to install it directly from the Play Store.

**Comment by AidanG1** [comment]
Any updates on F-Droid?

**Comment by msasikanth** [comment]
> Any updates on F-Droid?

Currently, my release process doesn't support F-Droid and it seems like some setup work is required to publish to F-Droid. So, I don't have any plans right now. Will do that once I finish some of my todo items.

**Comment by shuvashish76** [comment]
>  You should be able to install it directly from the Play Store.

@msasikanth There are many users like me who degoogled/debloated their device. Would be nice if you could publish the app on GitHub releases maybe @IzzySoft can pick it up for his [repo](https://apt.izzysoft.de/fdroid) (which is the largest 3rd-party F-Droid repo) untilled you're ready for official F-Droid repo...

**Comment by IzzySoft** [comment]
Size seems to fit (less than 6 MB per APK, if I see this correctly?) – and I don't see any "show-stoppers" from the `build.gradle.kts` (Sentry is opt-in I suppose?). So: Yes, I could do that – provided the APKs would be available at their corresponding releases (starting with the currently latest one and provided for future releases the same way, so my updater can fetch them automatically once they become available).

**Comment by msasikanth** [comment]
Let me look into it, right now the release process with Tramline is automated for working with app bundles. I have see if I can attach release APK to the release automatically.

**Comment by IzzySoft** [comment]
Thanks! And just give me a ping when I shall look :smiley:

**Comment by mrusme** [comment]
Would love to see an F-Droid release as well. Can the community support with this?

**Comment by SleepDaemon** [comment]
https://apt.izzysoft.de/fdroid/index/apk/dev.sasikanth.rss.reader

It's already on Izzydroid, but the latest version is 1.2.0

**Comment by IzzySoft** [comment]
> It's already on Izzydroid, but the latest version is 1.2.0

If the authors would not forget to attach the APKs to their corresponding releases, newer versions would be available as well :man_shrugging: @msasikanth maybe you can have a look and provide them? Starting with the latest release is fine, no need to fill in all older ones. No idea where the APK from v1.2.0 has gone to, seems not even that is there anymore.

**Comment by msasikanth** [comment]
I am working on adding the APKs back with releases. Hopefully I can get this done for the next version, I have already made the change to upload to GH Action for time being, will move that to releases soon.

**Comment by msasikanth** [comment]
Starting with [v1.39.1](https://github.com/msasikanth/twine/releases/tag/v1.39.1) new releases will have APK attached to them

**Comment by IzzySoft** [comment]
Thanks! Two questions on what my scanner reports:

```
Offending libs:
---------------
* Bugsnag exception reporter for Android (/com/bugsnag): Tracking

1 offenders.

Permissions:
------------
* android.permission.INTERNET
* android.permission.WAKE_LOCK
* android.permission.ACCESS_NETWORK_STATE
* android.permission.RECEIVE_BOOT_COMPLETED
* android.permission.FOREGROUND_SERVICE
* dev.sasikanth.rss.reader.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION

SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Is Bugsnag opt-in, or is it enabled by default? As for `DEPENDENCY_INFO_BLOCK`, that can easily be avoided:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by msasikanth** [comment]
Bugsnag is enabled by default to receive crash reports. It's not opt in. 

Any reason you require the dependency tree? Since it's open source you can already see it from my `libs.versions.toml` file.

**Comment by IzzySoft** [comment]
Thanks for your swift reply!

> Bugsnag is enabled by default

That means the `Tracking` anti-feature must be set then (as there was no consent acquired before its use).

> Any reason you require the dependency tree?

Just the other way around. It's currently in (Google made this the default Studio & Co). But as described, `DEPENDENCY_INFO_BLOCK` is encrypted with a Google key, so only Google can read it – and nobody else can even say what it really includes. Hence it's better disabled (at least for the APKs used in the FOSS world where there should be no such "opaque blobs"; if you distribute via PlayStore as well and they should require it, you could leave it active for the bundles you upload). `includeInApk = false` would ensure it's **NOT** included with the APKs (default of that is `true`, so currently it is in).
