### ISSUE TITLE
Support RTL text

### ISSUE THREAD

**Issue by iJahangard** [msasikanth/twine#396]
My mother tongue is Persian so the feeds i have are Persian
The problem is that Twine only support text alignment for left to right languages
So the arabic typescript will show up distorted when they contain English words in their sentences

**Comment by msasikanth** [comment]
Can you include a screenshot? If the device system language is set to RTL, that should work.

**Comment by othmahammedi** [comment]
![Screenshot_2024-05-25-19-31-37-336_dev.sasikanth.rss.reader.jpg](https://github.com/msasikanth/twine/assets/90103008/f1ca2276-87ac-4085-b8ed-598adb9518c3)

Article titles appear rtl when the system language is Arabic, but the content of the articles is ltr.

while the headings and content are ltr when the system language is

**Comment by othmahammedi** [comment]
The problem is still the same, for example, if I'm following articles in Arabic and English, the text alignment depends on the system language and therefore the text alignment is wrong in one article or even in the same article if it contains rtl and ltr languages.

![Screenshot_2024-08-01-20-08-27-544_dev.sasikanth.rss.reader.jpg](https://github.com/user-attachments/assets/ec4355e8-2748-43c8-afb6-6f442eaa1ac4)

![Screenshot_2024-08-01-20-08-39-599_dev.sasikanth.rss.reader.jpg](https://github.com/user-attachments/assets/af2027af-2bf4-4177-92ca-bb1606adcbd3)

**Comment by msasikanth** [comment]
Can you post the links to the feeds you are having this issue with? I can test it out and roll out a fix.

**Comment by othmahammedi** [comment]
https://discourse.aosus.org/latest.rss

https://fariszr.com/index.xml

**Comment by msasikanth** [comment]
I think this might take a lot more effort than I originally though. The easy option is what we have now, which would rely on the device language. Unfortunately anymore than that, requires identifying language at runtime and then updating the web page essentially. Will have to revisit that approach later on.

**Comment by othmahammedi** [comment]
See RTL support Implementation in Read you Maybe it will help you 

https://github.com/Ashinch/ReadYou/pull/378

**Comment by msasikanth** [comment]
Can you share an image that contains the right language direction for the above content so that I can verify the changes when I get to this?

**Comment by msasikanth** [comment]
I think I addressed the issue. The app will no longer depend on just the system language, it will depend on the content language as well.

In terms of mixed languages, it's rendering correctly as far as I can tell. When I check the links on my system in a browser, it displays in the same way. So, not much I can do in that aspect.

Here are few screenshots for the preview

![Screenshot_20240807_202844](https://github.com/user-attachments/assets/188da8b1-4475-49f4-932a-91d637eeb50a)
![Screenshot_20240807_202847](https://github.com/user-attachments/assets/873a3c58-5951-48e6-859c-71ae6628a77c)
![Screenshot_20240807_202850](https://github.com/user-attachments/assets/b9d81756-48d9-4c11-8776-e076e14547d6)

**Comment by othmahammedi** [comment]
Thank you for your response, I tried the latest version of github action and the result is good for both rtl and ltr, but there is a problem in displaying Code snippets, it shows rtl instead of ltr
