### ISSUE TITLE
All articles in RSS feed are sporadically reset to unread (Part II)

### ISSUE THREAD

**Issue by akinsho** [msasikanth/twine#405]
**Describe the bug**
Articles for my [Stratechery](https://stratechery.com/) RSS feed are sporadically reset to being "unread" after I refresh the feed. The link is https://stratechery.passport.online/feed/rss/Nd467Kzi7X9BZFFsnxuqv3 but it is personalised I think so not sure what will happen if you attempt to use it. I think this maybe similar to #186. If it is in fact like the previous issue then it's likely a bug of how the time format for that feed

**To Reproduce**
1. Add the Stratechery RSS feed either the one I provided or visit the website and sign up for one (I think each link is custom maybe)
2. Select the newly added feed
3. Mark all the stories which are downloaded as read
4. Refresh several times
5. Stories will re-appear as unread

**Device Information**
 - Device: Pixel 8 Pro
 - OS: Android 14
 - App Version: Latest (as of 25/03/24)

**Comment by msasikanth** [comment]
Hey. I tried to reproduce this issue on the latest version of the app (1.39.1) with the provided link, and cannot reproduce it. I tested it on both Android and iOS, and the posts read status is not getting reset.

Can you reproduce this issue with a video?

**Comment by msasikanth** [comment]
One possible cause for this would be the access token in the links. It might be changing, so a new link is created. We consider links as a unique key when saving the feed items.

**Comment by akinsho** [comment]
I'll try to get a video of this happening, it seems to be when I refresh the feed and there's been a new article published then it resets a bunch of the read ones

**Comment by akinsho** [comment]
I managed to get a screen recording after it happened. I just refreshed all my feeds to see any new articles and it happened again.

https://github.com/msasikanth/twine/assets/22454918/de80eaaf-9b95-4c48-8089-b3327af2a4f1

**Comment by msasikanth** [comment]
Looks like that feed is generating new links every time there is an update. That's causing to save duplicate news articles. There isn't much I can do about it.

**Comment by msasikanth** [comment]
I will note this down and see if there is a better way to handle this in future

**Comment by akinsho** [comment]
@msasikanth do you mean the links for each article are new? or the RSS link since I think that has been constant. If the article links are changing could a combination of the metadata instead be used as the identifier e.g. title + publish data + author or something
