### ISSUE TITLE
Mark all read button

### ISSUE THREAD

**Issue by uggrin** [msasikanth/twine#413]
Hello, 

I've just installed the app and I think it's one of the best RSS readers out there! And I've tried many. 

But, besides other useful features I'd like, I would really like to have a mark all read button. It's a very useful feature, and I'd imagine a pretty simple one to implement. 

Thanks and the app rocks!

**Comment by walrus543** [comment]
Mark read above/below the selected item too.
Thank you!

**Comment by Humorist2601** [comment]
The only major thing missing from this app imo.
