### ISSUE TITLE
Material You theming

### ISSUE THREAD

**Issue by appuchias** [msasikanth/twine#46]
Would it be possible to add Material You theming support to the app? 

I'm not involved in coding Android apps so I don't know how hard it could be, but it would be great to have the app integrate with the theme most of my apps and my launcher follow.

Thanks in advance for any update.

**Comment by msasikanth** [comment]
App already follows Material You content based theming, I have no plans on support wallpaper based theming for the app at the moment.

I will probably add themed icon in the next update
