### ISSUE TITLE
Hope to provide the APK file

### ISSUE THREAD

**Issue by WindWash** [msasikanth/twine#523]
We hope you can provide the APK file because we cannot access the Google Play Store. Thank you.

**Comment by msasikanth** [comment]
Forgot about it. It's available in the latest release now

**Comment by IzzySoft** [comment]
@msasikanth missing at the now-latest release :wink:

**Comment by IzzySoft** [comment]
Oh, PS: badge missing in the readme. Be welcome to [pick one](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and [point its link here](https://apt.izzysoft.de/packages/dev.sasikanth.rss.reader) :wink:
