### ISSUE TITLE
Apostrophe rendered as &apos; in feeds page 

### ISSUE THREAD

**Issue by nesper8** [msasikanth/twine#526]
**Describe the bug**
As title says

**To Reproduce**
1. Have an article with apostrophe in the title
2. Apostrophe will be rendered as`  &apos;`

**Screenshots**
![Screenshot_20240510-092650.png](https://github.com/msasikanth/twine/assets/57890520/20721059-f402-4537-821f-15f3fd03e8ab)

**Device Information**
 - Device: Motorola G32
 - OS: Android 13
 - App Version: 1.40.1 (435)

**Comment by msasikanth** [comment]
Fixed. Should be available from 1.43.0

**Comment by nesper8** [comment]
Fix confirmed 

Thank you very much
