### ISSUE TITLE
[Feature Request] Hide bottom bar

### ISSUE THREAD

**Issue by ntnguyen1234** [msasikanth/twine#527]
Hi, could there be any ways to hide the bottom bar? Currently I don't have any sources pinned so it's kind of wasting space here:

<details><summary>Screenshot</summary>

![twine](https://github.com/msasikanth/twine/assets/23257168/3a1980f1-7b1a-4684-ac87-cbf9016b1f3a)

</details>

Thank you again for your app.

**Comment by msasikanth** [comment]
Hi, thanks for the feedback. Unfortunately it's a core navigation element to swipe up and see all feeds. So we cannot remove it.
