### ISSUE TITLE
Swipe to mark as read

### ISSUE THREAD

**Issue by kacperwyczawski** [msasikanth/twine#537]
I'd really appreciate if there was a feature in this nice app, to swipe an entry in order to mark it as read.

Also, it would be nice addition to [#413](https://github.com/msasikanth/twine/issues/413#issue-2216309413)

Thanks in advance.

**Comment by msasikanth** [comment]
This is not planned for the app

**Comment by kacperwyczawski** [comment]
I understand, thanks for reply.
