### ISSUE TITLE
Ğ and ğ character problem

### ISSUE THREAD

**Issue by symbuzzer** [msasikanth/twine#548]
Cant use Turkish specific Ğ and ğ characters when naming feed links.

Pressing Ğ on keyboard writes G, pressing ğ on keyboard writes g

**Comment by msasikanth** [comment]
Can you include screenshots of where the issue is?

**Comment by symbuzzer** [comment]
O everywhere sir:
![photo1716627604](https://github.com/msasikanth/twine/assets/9841184/cd035712-fce1-48d7-901c-1d597da1833f)

**Comment by msasikanth** [comment]
Hmm, looks like it's a missing character in the font I am using. I will raise a issue with the font creators if possible, or else need to figure out how to handle it better.

https://fonts.google.com/specimen/Golos+Text/glyphs

**Comment by symbuzzer** [comment]
any news?

**Comment by CKopoer** [comment]
> Hmm, looks like it's a missing character in the font I am using. I will raise a issue with the font creators if possible, or else need to figure out how to handle it better.
> 
> https://fonts.google.com/specimen/Golos+Text/glyphs

I love your app, but the font problem brother me for a long time especially when reading Chinese rss sources. Maybe it's a better choice to alter the default font to support more character aside Engilish alphabet? Or could you provide an option to choose font of app? thanks for your masterwork.
