### ISSUE TITLE
Backup/Restore all RSS links

### ISSUE THREAD

**Issue by sv1sjp** [msasikanth/twine#56]
**Is your feature request related to a problem? Please describe.**
When you want to switch to a new device or format your phone, you cannot easily export all of your RSS feed links into a file and then restore it to your new device.

**Describe the solution you'd like**
E.g. export the database of the app into a file and save it to /sdcard . Also, the ability to restore the database from a specific file stored in user's storage.

**Additional context**

**Comment by sv1sjp** [comment]
Something like this for backup in json?

```
import android.content.Context
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.io.File

class Repository(private val queries: ReaderQueries, private val context: Context) {
    fun backupData() {
        val feeds = queries.feeds().executeAsList()
        val posts = queries.posts().executeAsList()

        val jsonFeeds = Json.encodeToString(feeds)
        val jsonPosts = Json.encodeToString(posts)

        File(context.filesDir, "feeds_backup.json").writeText(jsonFeeds)
        File(context.filesDir, "posts_backup.json").writeText(jsonPosts)
    }
}
```

**Comment by ghost** [comment]
At least use a standard. RSS readers usually backup to OPML format.

**Comment by msasikanth** [comment]
> At least use a standard. RSS readers usually backup to OPML format.

Yep, will implement support for importing and exporting OPML instead. Tracking it in #24
