### ISSUE TITLE
Error when adding a feed

### ISSUE THREAD

**Issue by Ze-Nyx** [msasikanth/twine#58]
**Describe the bug**
When I try to add any rss feed i get the error msg "CLEARTEXT communication not permitted by network security policy"

**Screenshots**
![Screenshot_2023-07-13-14-32-52-99_f399cc1ded1bced82d9d5339fe0d251e.jpg](https://github.com/msasikanth/reader/assets/67624161/19b1e28a-6a23-4ca5-be8a-7e911afa28fd)

**Device Information**
 - Device: OnePlus 8 pro 
 - OS: Android 13
 - App Version 1.4.0

**Comment by msasikanth** [comment]
App only supports links with `https` and not `http`
