### ISSUE TITLE
Multiple RSS Feed Issues (Possible Feed URL parsing issue?)

### ISSUE THREAD

**Issue by akinsho** [msasikanth/twine#587]
**Describe the bug**
For 2 of the RSS feeds I have added to Twine I encounter the following issues.
1. For a tech blog called *[Garbage Day](https://www.garbageday.email/)* link [here](https://rss.beehiiv.com/feeds/owMwaGYU36.xml) when a new article comes out and I click on it, it links me to the preview image not the actual site/article. I have also noticed that after a while it stops showing new articles. Please note that a few months ago 3 or so it worked perfectly fine (I didn't quite have time to raise the issue till just now)
2. Another feed of mine the *[Ars Technica](https://arstechnica.com/rss-feeds/) Gadget lab RSS feed* **crashes** ([link here](https://feeds.arstechnica.com/arstechnica/gadgets)) when I try to open a new article from that site i.e. the whole app crashes.

**To Reproduce**
1. Open Twine and add the links for both feeds
3. Open any Garbage day article and you'll see that you are taken to just the image
4. Open one of the gadget lab articles and it should crash the app

**Screenshots**

**Device Information**
 - Device: Pixel 8
 - OS: Android 14
 - App Version: latest

**Comment by msasikanth** [comment]
I have redone the reader view in newer commits. The app doesn't seem to be showing these issues the development builds now. I will be pushing an update soon*.  

For now I am gonna go ahead and close it since I cannot reproduce it on latest commits, you can reopen it if it repeats on the update again.

**Comment by msasikanth** [comment]
Reader view changes are done in this PR
https://github.com/msasikanth/twine/pull/545

**Comment by akinsho** [comment]
@msasikanth I'm now actually seeing a regression because I can no longer add the [Garbage Day](https://www.garbageday.email/) RSS to Twine at all I now get the same error as in #589 so I think the validation of RSS links has regressed

**Comment by akinsho** [comment]
FWIW the Feeder app is FOSS and it seems to be able to handle the various links. It's also written in Kotlin so it's validation library might be useful since they might have already handled a bunch of edge cases: https://github.com/spacecowboy/Feeder/blob/master/app/src/main/java/com/nononsenseapps/feeder/contentprovider/RssContentProviderContract.kt

**Comment by msasikanth** [comment]
I am working on some changes for the parser to improve this in next update.

**Comment by akinsho** [comment]
I just tried the newest version of the app and I find that when I add the RSS feed I mention above for garbage day, when I click on any article (note I read them in the webview not the reader view) it only shows the header image for the article it does not open the full webpage
