### ISSUE TITLE
Unable to add an RSS link (Stratechery mailing list/blog)

### ISSUE THREAD

**Issue by akinsho** [msasikanth/twine#589]
**Describe the bug**
An RSS feed I was previously able to add to Twine is now no longer working i.e. I get an error saying the link is an invalid RSS/Atom feed the link is [here](https://stratechery.passport.online/feed/rss/Nd467Kzi7X9BZFFsnxuqv3). I added this feed to the [Feeder app](https://play.google.com/store/apps/details?id=com.nononsenseapps.feeder.play&hl=en) and it was added fine. I've also not observed the same issue that I previously described in #405 in that app.

I recall that we discussed that maybe the RSS link was what was changing so it kept making duplicates. 
https://github.com/msasikanth/twine/issues/405#issuecomment-2022800560

I'm not sure this is the case as you can see if you look at the link itself it is the same now as it was when I first opened the issue.

One thing I noticed with Feeder is that it has an option to create unique UUIDs for articles if they are unstable for any reason, I didn't test long enough to see if that would be necessary as new articles are released infrequently but thought it was worth mentioning as it could be a good solution to that issue as a workaround

![Screenshot_20240529-185117.png](https://github.com/msasikanth/twine/assets/22454918/8ca568fa-7b5b-4f65-a807-fffa5e8658fd)

**Comment by msasikanth** [comment]
Hey Akinsho thanks for reporting the issue, I do generate a UUID based on the RSS item link we receive.

You can use this link https://validator.w3.org/feed/ to validate a feed that might not be added. It's usually some issue with the feed XML thats causing the parsing to fail. I will have to improve the app to handle such scenario as well. But it's a bit of a work.

**Comment by rickdtc** [comment]
I'm having kind of the same problem, a person who has twine 1.34.0, is able to add [this feed](https://thisweek.gnome.org/index.xml) but not on this current 1.43.0 version, the validator says the link is valid

**Comment by akinsho** [comment]
I just tried the latest version with a new feed link that definitely works in the validator you posted but not in the app [this](https://world.hey.com/dhh/feed.atom)

The original link I posted also doesn't work in the latest release

**Comment by msasikanth** [comment]
I am reverting some parser changes I made in the last couple of releases to improve reliability. I am trying to find the balance between reliability and performance to avoid crashes when there are lot of feeds. So, it will take sometime to fine tune that.
