### ISSUE TITLE
Marking Pinned Items using A Pin Icon instead of Separate Section

### ISSUE THREAD

**Issue by Humorist2601** [msasikanth/twine#622]
Hello

I wanted to ask if instead of the current implementation, it could be done so that there is no pinned section in the feed list rather the pinned items have a pinned icon infront of them. 

Currently it looks weird when the feed list is set the the List View as it goes from List (Pinned Items) > Grid (Groups) > List (Feeds)

![ResizedImage_(1080)x(2131)2024-06-25_15-34-31_7833](https://github.com/msasikanth/twine/assets/97790626/3ed44bed-90fb-4215-87b0-b8047f825a1d)

**Comment by msasikanth** [comment]
Accessibility wise it won't as the icon will be small size or truncates other content. That's reason it's in a context menu rather than icon.
