### ISSUE TITLE
There's something wrong about Chinese character encoding

### ISSUE THREAD

**Issue by CKopoer** [msasikanth/twine#627]
**Describe the bug**
Some Chinese characters aren't able to be displayed properly on titles which looks like there exists bugs about character encoding. Otherwise, it's shown well in the   article.

**Reproduce**
subcribe this rss for example: https://www.ithome.com/rss/

**Screenshots**
![Screenshot_2024-06-30-23-54-04-416_dev.sasikanth.rss.reader.jpg](https://github.com/msasikanth/twine/assets/52709412/1a56a808-3ff9-4241-a37f-0d5079d945d3)

**Device Information**
 - Device: Xiaomi 13
 - OS: Android 14
 - App Version: 1.45.0（518）

**Stacktrace**
If present, add stacktrace to help debug the issue faster.

**Comment by CKopoer** [comment]
Maybe it is due to the font which can't display all characters in Chinese

**Comment by CKopoer** [comment]
It seems that this problem still exists in version 1.46.0
![lQDPJwRZ-r7Z6SPNCWDNBDiwZQnCOuyGo1UGjrTLlI3yAA_1080_2400](https://github.com/user-attachments/assets/02e38c02-ce4d-4ca4-bdff-fd06f39d46a3)

**Comment by msasikanth** [comment]
I haven't published the new app yet. Will be available in next update.

**Comment by CKopoer** [comment]
> I haven't published the new app yet. Will be available in next update.

Thanks for your work!!! Cant wait to receive the latest version.
