### ISSUE TITLE
https://www.nature.com/nature.rss doesn't work

### ISSUE THREAD

**Issue by sijvert** [msasikanth/twine#630]
When trying to add https://www.nature.com/nature.rss, the app tells me "link doesn't contain any rss/atom feed"

Link works in other rss reader

**Device Information**
 - Device: nothina 2a
 - OS: Android 14
 - App Version 1.45

The app looks phenomenal btw. Love it!

**Comment by msasikanth** [comment]
It's RSS v1.0 feed, duplicate #183
