### ISSUE TITLE
News date reset on every refresh

### ISSUE THREAD

**Issue by Golem642** [msasikanth/twine#632]
**Describe the bug**
Every time I refresh the feed list (or I just open the app since it does that automatically), the date/time where the news were created resets back to 0min.
So in essence, they never get deleted automatically and i don't know when those were actually created/pulled to my device for the first time

**To Reproduce**
1. Open the app or refresh the feed list
2. Every news will go back to 0min

**Screenshots**
![Screenshot_2024-07-10-00-33-23-944_dev.sasikanth.rss.reader.jpg](https://github.com/msasikanth/twine/assets/65229557/82534355-bbcc-4598-946b-b305159384e5)

**Device Information**
 - Device: Xiaomi Redmi Note 11
 - OS: MIUI 13.0.6, Android 12
 - App Version: 1.44.1

**Comment by Golem642** [comment]
Also side problem : some website icons never load as you can see on the bottom row, I got the second one to load at some point but now it doesn't work anymore. Isn't there a way to force refresh these ?

**Comment by msasikanth** [comment]
It's resolved, and should be available in future releases. Reference: #427

**Comment by Golem642** [comment]
> Also side problem : some website icons never load as you can see on the bottom row, I got the second one to load at some point but now it doesn't work anymore. Isn't there a way to force refresh these ?

What about this ? @msasikanth

**Comment by msasikanth** [comment]
Unfortunately no, they will get reset at some point. If a website has a favicon it tries to fetch it and cache that, so it will get refresh every few hours or sometime can take a day or two.
