### ISSUE TITLE
Cannot Add the Following Atom Feed

### ISSUE THREAD

**Issue by Humorist2601** [msasikanth/twine#634]
**Describe the bug**
Hello, I am trying to add a certain atom feed but it is not working. I click the button but nothing happens. The feed is this one 
https://releasefeed.elomatreb.eu/releases/spotify/2YZyLoL8N0Wb9xBt1NhZWg

**Device Information**
 - Device: Pixel 4a 5g
 - OS: Androud 14
 - App Version: 1.193.0

**Comment by msasikanth** [comment]
Looks like the items in the feed are missing a URL to point to, the app requires the `link` tag to be present in atom feeds, since it need to figure out what to open on certain click actions.
