### ISSUE TITLE
Feeds not loading / slow loading at start

### ISSUE THREAD

**Issue by TronTheGamer** [msasikanth/twine#646]
**Describe the bug**
The feeds source and groups don't load when starting the app most of the time. Takes a lot of time for the feeds and feed groups to load

**To Reproduce**
1. Add feeds and groups
2. Close the app and start

**Screenshots**
![Screenshot_2024-07-25-08-26-24-924_dev.sasikanth.rss.reader.jpg](https://github.com/user-attachments/assets/1ebd6b12-c26a-4dd0-9c9a-cbb81fb8fa17)

![Screenshot_2024-07-25-08-26-27-784_dev.sasikanth.rss.reader.jpg](https://github.com/user-attachments/assets/ec5d3392-dfd3-4afa-9ec9-a7773f33c420)

**Device Information**
 - Device: Xiaomi 11i Hypercharge
 - OS: Android 13
 - App Version 1.46.0

**Stacktrace**

**Comment by msasikanth** [comment]
Made some changes to how feed lists are loaded, it should be a little faster now. Should be available in next update.
