### ISSUE TITLE
Long-press context menu

### ISSUE THREAD

**Issue by br0tda** [msasikanth/twine#674]
Hi,
It would be great to have a "context menu" accessibile from a long press on the icon's feed in the tab of pinned ones.

In this menu, options like "mark as read" could take place. 

Here is an easy concept in the screen![Screenshot_20240728_184744_Twine.jpg](https://github.com/user-attachments/assets/bf5e6f48-d77e-41ab-b87f-f2cecfacccbc)

**Comment by msasikanth** [comment]
There will be a dedicated mark as read button in home screen instead in next update. 

https://github.com/msasikanth/twine/issues/413
