### ISSUE TITLE
Cannot enable notifications

### ISSUE THREAD

**Issue by DMJoh** [msasikanth/twine#676]
**Describe the bug**
No notifications from the app. I cannot turn on this as well in App settings.

**To Reproduce**
1. Long press on app icon
2. Go to Settings
3. Try enable notifications, but nothing happens.

**Device Information**
 - Device: Samsung S22 plus
 - OS: Android 14
 - App Version: 1.46.0

**Comment by msasikanth** [comment]
duplicate #296
