### ISSUE TITLE
Allow rearranging RSS feeds order

### ISSUE THREAD

**Issue by krishnaar21** [msasikanth/twine#68]
Its abit painful to not have some of my favourite RSS sources at first as app takes the orde in chronological form. 

It would be really helpful if we can reorder the added sources and any newly added source goes to bottom of the list.

**Comment by msasikanth** [comment]
Yep, that's next on my plate. _(I have added a handful of TODO items in the README)_

**Comment by msasikanth** [comment]
Decided to not support full reordering as that requires significant work. Instead added pinned section to feeds, where you can pin 10 feeds that you want to show up in the homescreen bottom bar.
