### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by samolukadjo** [msasikanth/twine#714]
**Is your feature request related to a problem? Please describe.**
When the mark all as read and delete feed functionality are used on a feed with more than several dozen unread posts there is a wait while the action is executed but the app does not communicate this in any way. If the user attempts to use the app whilst it's trying to delete a feed or mark items in a feed as read the app won't work.

This is okay when the wait is a few seconds, but when it's a few minutes then that becomes a problem.

**Describe the solution you'd like**
When an action that commonly takes a long time is called a progressbar should be there to inform the user that something is happening and that progress is being made towards the actions completion. Preferably the progressbar would also show the number of feed items that still need to be marked as read/deleted.

**Additional context**
N/A

**Comment by msasikanth** [comment]
Typically this action is always fast, even with hundreds of posts. But in a older version I made change that affected the performance, since then I resolved it and update is available. 

Closing it now

**Comment by msasikanth** [comment]
If the issue still exists, feel free to reopen this
