### ISSUE TITLE
unable to add a rss feed

### ISSUE THREAD

**Issue by nick-77** [msasikanth/twine#717]
Hi, im unable to add this specific rss feed “ http://www.autocarindia.com/RSS/RSS.ashx ”
Whenever I try to add it, it gives "Failed to connect to localhost /127.0.0.1:443"

1. Click on add a new feed
2. Enter
http://www.autocarindia.com/RSS/RSS.ashx
4. Click on add feed, see error 

![0ARX9RxmRj8P54XI0qVfmcxeFRV9sszr.jpg](https://github.com/user-attachments/assets/c9b45a23-cd00-4116-bf08-ccac2753cbda)

**Feed Information**
http://www.autocarindia.com/RSS/RSS.ashx

**Device Information**
 - Device: Realme Gt 2 pro
 - OS: Realme UI 5.0, Android 14
 - App Version 1.47.1

**Comment by msasikanth** [comment]
duplicate #493
