### ISSUE TITLE
Move scroll to top to bottom of the screen

### ISSUE THREAD

**Issue by FluffyDiscord** [msasikanth/twine#720]
**Describe the bug**
Dismissing bottom bar doesnt update the scroll to top button position.

**To Reproduce**
1. Open the app
2. Dismiss bottom bar
3. Scronn down until button appears

**Screenshots**
![Screenshot_20240821_090029_Twine](https://github.com/user-attachments/assets/4dd874be-cbac-41ac-a36e-73ae45525516)

**Feed Information**
-

**Device Information**
 - Device: Samsung S23 Ultra
 - OS: Android 14
 - App Version: 1.48.1

**Stacktrace**
-

**Comment by FluffyDiscord** [comment]
On the side note - keep the bottom bar hidden, if I dissmiss it, it takes too much space for no good reason. It vould be an option in settings or in the top right menu button dropwdown

**Comment by msasikanth** [comment]
Bottom bar is the navigation area in this app for feed management. It won't be hidden. 

Currently there is a bug which is causing it to be hidden when you swipe down. But that will be fixed in later releases. 

With bottom bar in place, the scroll to top button is exactly where it's supposed to be.

**Comment by FluffyDiscord** [comment]
Oh, i found that actually useful, because as i mentioned, it steals pretty big chunk of the reader area

**Comment by msasikanth** [comment]
> Oh, i found that actually useful, because as i mentioned, it steals pretty big chunk of the reader area

I hear you. I think one of the options we can try out is hiding app bar which also takes up space during scroll. That way users have more space to explore the articles.
