### ISSUE TITLE
Too much time to load article 

### ISSUE THREAD

**Issue by mjain234** [msasikanth/twine#721]
**Description:**

Hello! I'm experiencing an issue with loading articles on the platform. Often, it takes an excessively long time to load articles, which is frustrating . Despite a stable internet connection, the loading time is consistently taking more than 30 seconds.

**Expected Result:**

The article should load quickly, within a few seconds, and the page should be responsive throughout the loading process.

**Actual Result:**

The article takes a long time to load, and the page may become unresponsive or freezing during the loading process.

**System Information:**

* Operating System: Nothing OS
* Android version: Android 14

I'd appreciate any help or guidance in resolving this issue.

**Comment by br0tda** [comment]
Hi, I wanna add that even "mark as read" from the single "news card" is slower than before.

**Comment by msasikanth** [comment]
> **Description:**
> 
> 
> 
> Hello! I'm experiencing an issue with loading articles on the platform. Often, it takes an excessively long time to load articles, which is frustrating . Despite a stable internet connection, the loading time is consistently taking more than 30 seconds.
> 
> 
> 
> **Expected Result:**
> 
> 
> 
> The article should load quickly, within a few seconds, and the page should be responsive throughout the loading process.
> 
> 
> 
> **Actual Result:**
> 
> 
> 
> The article takes a long time to load, and the page may become unresponsive or freezing during the loading process.
> 
> 
> 
> **System Information:**
> 
> 
> 
> * Operating System: Nothing OS
> 
> * Android version: Android 14
> 
> 
> 
> I'd appreciate any help or guidance in resolving this issue.

Can you include posts from what source are slow to load? Some pages are slow to load because of larger content, so just want to make sure to test it.

**Comment by mjain234** [comment]
As you can see [here](https://github.com/user-attachments/assets/d6b396a0-f779-4008-b0bb-8b562b181c26), despite being good connection, Twine is having trouble opening the pages. Don't know what's the issue here :⁠-⁠\

**Comment by msasikanth** [comment]
This issue should be now resolved for both loading the list of articles and article reader view with

https://github.com/msasikanth/twine/commit/c0715e8093006c80028c8d12020af1b549c9f6b1 and https://github.com/msasikanth/twine/commit/8bf1d81fd54d0a0984c96c3e02d2b1d55f736cc5

**Comment by mjain234** [comment]
Didn't get you, what should I do?

**Comment by msasikanth** [comment]
These fixes should be available in the next update
