### ISSUE TITLE
I can't add the RSS feed made by the self-built server.

### ISSUE THREAD

**Issue by MadQHawk** [msasikanth/twine#722]
**Describe the bug**

I built a web page to generate an RSS source on my own server, and the source prompted an error in the application. I can be sure that my source is fine, because it can be recognized by some other RSS readers.

[image](https://github.com/user-attachments/assets/b5935e5a-41a4-45c8-93f3-745023097cd0)

**Device Information**
 - Device: iPhone 15
 - OS: IOS18
 - App Version 1.48.1!

**Stacktrace**
If present, add stacktrace to help debug the issue faster.

**Comment by msasikanth** [comment]
Currently http URLs are not supported #493
