### ISSUE TITLE
Light Mode

### ISSUE THREAD

**Issue by PitiBouchon** [msasikanth/twine#725]
When I'm in light mode everything is light except the "down bar" and its settings

![Screenshot_2024-09-04-01-53-53-68_f399cc1ded1bced82d9d5339fe0d251e.jpg](https://github.com/user-attachments/assets/89ddc56e-a307-4b6c-8327-bde3bdd7d652)

**Comment by msasikanth** [comment]
Intended behaviour of the contrast reasons.

**Comment by PitiBouchon** [comment]
I find this strange to be intended. It means swiping (from down to up) will completely change your screen from from a flashy white background to a complete dark one
