### ISSUE TITLE
Feed parsed partially

### ISSUE THREAD

**Issue by andreyorst** [msasikanth/twine#738]
**Describe the bug**
The reader view doesn't provide full content of the article, no matter if fetch full is active or not.

**To Reproduce**
1. Add the https://clojure.org/feed.xml feed
2. Click on any of the Clojure Deref posts
3. See error

**Screenshots**
Fetch full not pressed:

![image](https://github.com/user-attachments/assets/a53ed16d-47ad-43b9-82b4-01b38d336325)

Fetch full pressed:

![image](https://github.com/user-attachments/assets/71d4819e-a036-472b-8d93-a1600a2445f2)

Screenshot of another RSS reader that has a similar reader view feature:

![image](https://github.com/user-attachments/assets/fa9b4c17-c9b3-41d9-b7f4-4ac6fb2f6f35)

If I disable fetch full in that reader it goes to the same content as Twine:

![image](https://github.com/user-attachments/assets/6ad44937-cc5f-4573-9a82-b671357aff18)

**Feed Information**

https://clojure.org/feed.xml

The feed itself is missing it's latest post for some reason. Not a problem in another RSS reader, so maybe another bug.

**Device Information**
 - Device: Samsung S23U
 - OS: Android 14
 - App Version 1.48.1

**Comment by msasikanth** [comment]
This seems to be working as expected with the [parser](https://reader.postlight.com/) I am using for the reader view. Unfortunately not much I can do about it 😓

**Comment by andreyorst** [comment]
FYI, I updated to the 1.49.1 and this still happens to me with another feed:

![Screenshot_20241015_035544_Twine](https://github.com/user-attachments/assets/0f71c502-800e-4a4c-874c-489693183eab)
![Screenshot_20241015_035554_Firefox](https://github.com/user-attachments/assets/537dfa8d-dbb2-427b-ba40-624704c558e1)

happened with this feed: https://sachachua.com/blog/feed/
