### ISSUE TITLE
Error reporting for invalid URLs is confusing

### ISSUE THREAD

**Issue by msfjarvis** [msasikanth/twine#92]
**Describe the bug**

Entering an incorrect URL surfaces errors that range from confusing to misleading.

| Input URL | Error message | Suggested fix |
|-----------|---------------|---------------|
|`msfjarvis.dev/feed.xml`|Unable to connect to localhost/127.0.0.1:443|Default URL scheme to HTTPS if absent|
|`https://msfjarvis.dev/feed.xml`|App doesn't support this type of feed yet|Special case handling of HTTP 404|

**Device Information**
 - Device: Pixel 4a
 - OS: Android 13
 - App Version: 1.16.0

**Comment by msasikanth** [comment]
Yeah, I was putting handling response codes properly in backlog for a while. Will pick it up soon 🙈

For the HTTP protocol, I do set it as HTTPS when making a request. I guess it's not applying if a protocol is not present? Interesting 🤔 

https://github.com/msasikanth/twine/blob/7f2980939b6b9f3222e19b6af5763fcbc76d03b3/shared/src/commonMain/kotlin/dev/sasikanth/rss/reader/network/FeedFetcher.kt#L31
